person<-read.table("movie_metadata.csv")
person
(persons_complete <- na.omit(person))
save(persons_complete,file="C:/Users/Patrick/Documents/complete.csv")
person2<-read.csv("complete.csv")
person2
player<-read.table(file="movie_metadata.csv",sep="\t",header=TRUE,quote="\"")
head(player)
names(player)
write.csv(persons_complete,"newfile.csv")
library(editrules) 
(E <- editset(c("title_year >=2000", "title_year <= 2016","title_year <=NA " )))
RULE<-violatedEdits(E, person)
summary(RULE)
plot(RULE)
RULE
write.csv(RULE,"file1.csv")
dim(person)
tail(person)
names(person)
mean(person$duration)
person$duration
attach(person)
detach(person)
mean(duration)
class(genres)
levels(genres)
summary(person)
person2000<-subset(person, title_year >=2001)
write.csv(person2000,"filenew1.csv")
read2<-read.csv("filenew1.csv")
names(read2)
read2$duration[which(is.na(read2$duration))]<-mean(read2$duration,na.rm=TRUE)
read2$actor_1_facebook_likes[which(is.na(read2$actor_1_facebook_likes))]<-mean(read2$actor_1_facebook_likes,na.rm=TRUE)
read2$actor_2_facebook_likes[which(is.na(read2$actor_2_facebook_likes))]<-mean(read2$actor_2_facebook_likes,na.rm=TRUE)
read2$actor_3_facebook_likes[which(is.na(read2$actor_3_facebook_likes))]<-mean(read2$actor_3_facebook_likes,na.rm=TRUE)
read2$cast_total_facebook_likes[which(is.na(read2$cast_total_facebook_likes))]<-mean(read2$cast_total_facebook_likes,na.rm=TRUE)
read2$facenumber_in_poster[which(is.na(read2$facenumber_in_poster))]<-mean(read2$facenumber_in_poster,na.rm=TRUE)
read2$imdb_score[which(is.na(read2$imdb_score))]<-mean(read2$imdb_score,na.rm=TRUE)
read2$movie_facebook_likes[which(is.na(read2$movie_facebook_likes))]<-mean(read2$movie_facebook_likes,na.rm=TRUE)
read2$num_critic_for_reviews[which(is.na(read2$num_critic_for_reviews))]<-mean(read2$num_critic_for_reviews,na.rm=TRUE)
read2$director_facebook_likes[which(is.na(read2$director_facebook_likes))]<-mean(read2$director_facebook_likes,na.rm=TRUE)
read2$gross[which(is.na(read2$gross))]<-mean(read2$gross,na.rm=TRUE)
read2$num_voted_users[which(is.na(read2$num_voted_users))]<-mean(read2$num_voted_users,na.rm=TRUE)
read2$num_user_for_reviews[which(is.na(read2$num_user_for_reviews))]<-mean(read2$num_user_for_reviews,na.rm=TRUE)
read2$budget[which(is.na(read2$budget))]<-mean(read2$budget,na.rm=TRUE)
read2$aspect_ratio[which(is.na(read2$aspect_ratio))]<-median(read2$aspect_ratio,na.rm=TRUE)

read2$director_facebook_likes[which(is.na(read2$director_facebook_likes))]<-mean(read2$director_facebook_likes,na.rm=TRUE)
write.csv(read2,"filenew2.csv")
read3<-read.csv("filenew2.csv")
(person4 <- na.omit(read3))
write.csv(person4,"filenew3.csv")
read4<-read.csv("filenew3.csv")
attach(read4)
library(caret)
summary(read4[1:28])
preprocessParams<- preProcess(read4[1:28], method=c("scale"))
print(preprocessParams)
transformed <- predict(preprocessParams, read4[1:28])
summary(transformed)
